name: Keep Streamlit App Awake

on:
  schedule:
    # Runs every 6 hours automatically
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer (Headless Browser)
        run: npm i puppeteer

      - name: Visit Streamlit App
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ args:['--no-sandbox', '--disable-setuid-sandbox'] });
            const page = await browser.newPage();
            try {
              console.log('Visiting the app...');
              await page.goto('https://fyp-mwedetection.streamlit.app/', { waitUntil: 'networkidle2', timeout: 60000 });
              console.log('Successfully visited to keep awake!');
            } catch (err) {
              console.error('Error visiting the app:', err);
            } finally {
              await browser.close();
            }
          })();
          "
